### ISSUE TITLE
해당 이슈 이벤트로그

### ISSUE THREAD

**Issue by Mccreate** [Dalbodre/posSolution#1]
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-10-06T03:08:21.000000000Z" /> 
  <EventRecordID>55975</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>POS</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>ARUMPOS.exe</Data> 
  <Data>1.0.0.0</Data> 
  <Data>60e896a8</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>6.1.7601.19135</Data> 
  <Data>56a1c680</Data> 
  <Data>e0434352</Data> 
  <Data>000080d7</Data> 
  <Data>1f24</Data> 
  <Data>01d7ba5f6677b5b7</Data> 
  <Data>C:\Users\Administrator\Desktop\posSolution\ARUMPOS.exe</Data> 
  <Data>C:\Windows\system32\KERNELBASE.dll</Data> 
  <Data>a8beaa21-2652-11ec-b6f7-00e0b41523fb</Data> 
  </EventData>
  </Event>

**Comment by Mccreate** [comment]
로그 이름:         Application
원본:            Application Error
날짜:            2021-10-06 오후 12:08:21
이벤트 ID:        1000
작업 범주:         (100)
수준:            오류
키워드:           클래식
사용자:           해당 없음
컴퓨터:           POS
설명:
오류 있는 응용 프로그램 이름: ARUMPOS.exe, 버전: 1.0.0.0, 타임스탬프: 0x60e896a8
오류 있는 모듈 이름: KERNELBASE.dll, 버전: 6.1.7601.19135, 타임스탬프: 0x56a1c680
예외 코드: 0xe0434352
오류 오프셋: 0x000080d7
오류 있는 프로세스 ID: 0x1f24
오류 있는 응용 프로그램 시작 시간: 0x01d7ba5f6677b5b7
오류 있는 응용 프로그램 경로: C:\Users\Administrator\Desktop\posSolution\ARUMPOS.exe
오류 있는 모듈 경로: C:\Windows\system32\KERNELBASE.dll
보고서 ID: a8beaa21-2652-11ec-b6f7-00e0b41523fb
이벤트 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-10-06T03:08:21.000000000Z" />
    <EventRecordID>55975</EventRecordID>
    <Channel>Application</Channel>
    <Computer>POS</Computer>
    <Security />
  </System>
  <EventData>
    <Data>ARUMPOS.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>60e896a8</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.1.7601.19135</Data>
    <Data>56a1c680</Data>
    <Data>e0434352</Data>
    <Data>000080d7</Data>
    <Data>1f24</Data>
    <Data>01d7ba5f6677b5b7</Data>
    <Data>C:\Users\Administrator\Desktop\posSolution\ARUMPOS.exe</Data>
    <Data>C:\Windows\system32\KERNELBASE.dll</Data>
    <Data>a8beaa21-2652-11ec-b6f7-00e0b41523fb</Data>
  </EventData>
</Event>

추가정보

**Comment by Mccreate** [comment]
로그 이름:         Application
원본:            .NET Runtime
날짜:            2021-10-06 오후 12:08:21
이벤트 ID:        1026
작업 범주:         없음
수준:            오류
키워드:           클래식
사용자:           해당 없음
컴퓨터:           POS
설명:
Application: ARUMPOS.exe
CoreCLR Version: 5.0.921.35908
.NET Version: 5.0.9
Description: The process was terminated due to an unhandled exception.
Exception Info: MySqlConnector.MySqlException (0x80004005): Unknown column 'o.FranchiseNumber' in 'field list'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 135
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 314
   at MySqlConnector.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySqlCommand.cs:line 256
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__19_0(DbContext _, Enumerator enumerator)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ArumModels.Models.Order.GetOrdersByMonth(DateTime date, Int32 shopId) in C:\Users\lnb\source\repos\ARUMPOS\ArumModels\Models\OrderModels.cs:line 101
   at ARUMPOS.ViewModels.CalculateViewModel.BuildPage() in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\ViewModels\CalculateViewModel.cs:line 76
   at ARUMPOS.ViewModels.CalculateViewModel..ctor() in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\ViewModels\CalculateViewModel.cs:line 42
   at ARUMPOS.Views.CalculateView.!XamlIlPopulate(IServiceProvider , CalculateView ) in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\Views/CalculateView.axaml:line 1
   at ARUMPOS.Views.CalculateView.!XamlIlPopulateTrampoline(CalculateView )
   at ARUMPOS.Views.CalculateView.InitializeComponent() in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\Views\CalculateView.axaml.cs:line 18
   at ARUMPOS.Views.CalculateView..ctor() in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\Views\CalculateView.axaml.cs:line 13
   at ARUMPOS.Views.MainWindow.!XamlIlPopulate(IServiceProvider , MainWindow ) in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\Views/MainWindow.axaml:line 49
   at ARUMPOS.Views.MainWindow.!XamlIlPopulateTrampoline(MainWindow )
   at ARUMPOS.Views.MainWindow.InitializeComponent() in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\Views\MainWindow.axaml.cs:line 22
   at ARUMPOS.Views.MainWindow..ctor() in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\Views\MainWindow.axaml.cs:line 14
   at ARUMPOS.App.OnFrameworkInitializationCompleted() in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\App.axaml.cs:line 20
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 312
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 174
   at ARUMPOS.Program.Main(String[] args) in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\Program.cs:line 27

이벤트 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-10-06T03:08:21.000000000Z" />
    <EventRecordID>55974</EventRecordID>
    <Channel>Application</Channel>
    <Computer>POS</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: ARUMPOS.exe
CoreCLR Version: 5.0.921.35908
.NET Version: 5.0.9
Description: The process was terminated due to an unhandled exception.
Exception Info: MySqlConnector.MySqlException (0x80004005): Unknown column 'o.FranchiseNumber' in 'field list'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 50
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 135
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 444
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 60
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 314
   at MySqlConnector.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySqlCommand.cs:line 256
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.&lt;&gt;c.&lt;MoveNext&gt;b__19_0(DbContext _, Enumerator enumerator)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ArumModels.Models.Order.GetOrdersByMonth(DateTime date, Int32 shopId) in C:\Users\lnb\source\repos\ARUMPOS\ArumModels\Models\OrderModels.cs:line 101
   at ARUMPOS.ViewModels.CalculateViewModel.BuildPage() in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\ViewModels\CalculateViewModel.cs:line 76
   at ARUMPOS.ViewModels.CalculateViewModel..ctor() in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\ViewModels\CalculateViewModel.cs:line 42
   at ARUMPOS.Views.CalculateView.!XamlIlPopulate(IServiceProvider , CalculateView ) in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\Views/CalculateView.axaml:line 1
   at ARUMPOS.Views.CalculateView.!XamlIlPopulateTrampoline(CalculateView )
   at ARUMPOS.Views.CalculateView.InitializeComponent() in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\Views\CalculateView.axaml.cs:line 18
   at ARUMPOS.Views.CalculateView..ctor() in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\Views\CalculateView.axaml.cs:line 13
   at ARUMPOS.Views.MainWindow.!XamlIlPopulate(IServiceProvider , MainWindow ) in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\Views/MainWindow.axaml:line 49
   at ARUMPOS.Views.MainWindow.!XamlIlPopulateTrampoline(MainWindow )
   at ARUMPOS.Views.MainWindow.InitializeComponent() in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\Views\MainWindow.axaml.cs:line 22
   at ARUMPOS.Views.MainWindow..ctor() in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\Views\MainWindow.axaml.cs:line 14
   at ARUMPOS.App.OnFrameworkInitializationCompleted() in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\App.axaml.cs:line 20
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 312
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 174
   at ARUMPOS.Program.Main(String[] args) in C:\Users\lnb\source\repos\ARUMPOS\ARUMPOS\Program.cs:line 27
</Data>
  </EventData>
</Event>
